name: 'ngrok'

on:
  push:
    branches:
    - master

jobs:
  ngrokStart:
    runs-on: ubuntu-latest
    steps:
      - name: 'check codes'
        uses: actions/checkout@v2
      - name: 'start ngrok'
        run: sudo batch/ngrok.sh
