name: 'Python Works'

on:
  schedule:
    - cron: '5 16,22 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'check codes'
        uses: actions/checkout@v2
      - name: 'set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'start python'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python batch/main.py
